name: flutter_google_places_sdk_http
description: An http implementation of Flutter plugin to be used by other platform implementation
version: 0.1.4
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_http
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  latlong2: ^0.9.1
  flutter_google_places_sdk_platform_interface:
    path: ../flutter_google_places_sdk_platform_interface
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
dependency_overrides:
  freezed_annotation: ^3.0.0

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  mockito: ^5.4.0
