name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.10
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_platform_interface/
      ref: master
  flutter_google_places_sdk_ios: # ^0.1.6+1
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_ios/
      ref: master
  flutter_google_places_sdk_web: # ^0.1.8
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_web/
      ref: master
  flutter_google_places_sdk_android: # ^0.2.0-dev.2
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_android/
      ref: master
  flutter_google_places_sdk_windows: # ^0.1.4
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_windows/
      ref: master
  flutter_google_places_sdk_linux: # ^0.1.4
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_linux/
      ref: master
  flutter_google_places_sdk_macos: # ^0.1.4
    git:
      url: https://github.com/dario91sr/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_macos/
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
      linux:
        default_package: flutter_google_places_sdk_linux
      macos:
        default_package: flutter_google_places_sdk_macos
